/*
Note: Runtime is highly variable between submissions and I don't have a premium subscription,
  which places me in a lower tier.
Runtime: 98 ms, faster than 98.78% of JavaScript online submissions for Squares of a Sorted Array.
Memory Usage: 48.7 MB, less than 59.01% of JavaScript online submissions for Squares of a Sorted Array.

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

var findTheDifference = function(s, t) {
  let letters = {}
  for (a of s) letters[a] ? letters[a] ++ : letters[a] = 1
  for (b of t) {
    if (letters[b] > 0) letters[b] --
    else return b
  }
};

console.log(findTheDifference("abcd", "abcde"))
module.exports = findTheDifference